services:
  app:
    image: nazmulhasn/prashanthja_app:latest
    container_name: prashanthja_app
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=prashanthja_redis
      - REDIS_PORT=6379
    ports:
      - '4000:4000'
      - '4005:4005'
    depends_on:
      - redis
    command: ['node', 'dist/server.js']

  redis:
    image: redis:7.2-alpine
    container_name: prashanthja_redis
    ports:
      - 6380:6379
    volumes:
      - redis-data:/data
    restart: always
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  redis-data:
